chore(workflows): updated Github Action for stale issues/PRs
americanexpress/create-shared-react-context pull request #6
Opened 2020-04-09 10:01 UTC by NarmeenNaveedAhmed

This PR is to update GitHub action for stale issues/PRs so they are only labeled as stale but not auto-closed.

2020-04-17 10:42 UTC, infoxicator submitted a review, later dismissed

2020-04-22 19:50 UTC, asutedja submitted a review, later dismissed

2020-04-22 20:15 UTC, mtomcal submitted a review, later dismissed

2020-04-23 23:36 UTC, JAdshead requested changes
This needs to be updated to use `actions/stale@v2`

2020-05-14 21:27 UTC, JAdshead approved these changes

2020-05-27 04:12 UTC, closed without merging